apiVersion: v1
kind: Service
metadata:
  name: converge-api
  labels:
    app: converge
    component: api
spec:
  type: ClusterIP
  ports:
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: http
  selector:
    app: converge
    component: api
